# Generated by Django 4.2.3 on 2023-08-22 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filesmanager', '0006_delete_testmodel'),
        ('app', '0009_auto_20230822_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_path',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesmanager.media'),
        ),
        migrations.AddField(
            model_name='specification',
            name='icon_path',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='filesmanager.media'),
        ),
    ]
